import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppState from "@/context/appState";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "web.whatsapp.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {




  return (
    <html lang="en">
      <body className={inter.className}>
        <AppState>
          {children}
          <div id="photo-picker-element"></div>
        </AppState>
      </body>
    </html>
  );
}
